version: "3.8"

services:
  app:
    build: .
    container_name: next_app
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      pg_db:
        condition: service_healthy

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public
      - /etc/letsencrypt/live/dpsmaturitysurvey.org:/etc/letsencrypt/live/dpsmaturitysurvey.org:ro
      - /etc/letsencrypt/archive/dpsmaturitysurvey.org:/etc/letsencrypt/archive/dpsmaturitysurvey.org:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
    depends_on:
      - app

  pg_db:
    image: postgres:17
    container_name: next_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
